### PR TITLE
Various updates and fixes

### PR DESCRIPTION
**Pull request by sirmordred**
-set status within methods(fixes bug in connectedThread method)
-remove unnecessary calls(fixes multiple declaration)

### CODE REVIEW

**Comment by sirmordred** [comment]
I signed it!

And for note: I tested it and everything seems working good now
Thanx

**Comment by sirmordred** [comment]
ok ready to go :+1:

**Comment by MaxDZ8** [comment]
Is this merged?
I spent yesterday figuring out and fixing the race condition regarding `ConnectedThread`.

This patch includes much more than I did so I won't push mine but please update.

**This pull should be merged!** It should have been merged weeks ago!

Very bad to see android examples are not maintained at all!

**Comment by sirmordred** [comment]
+1 it is bad to see maintaining example repos are really slow,

and current app has race condition that we are talking about above so there is no two-way chat in android-bluetoothchat example app now. it is bad for people who is using this example.

i hope it will be merged soon :+1:

**Comment by yaraki** [comment]
Thank you so much and sorry for being late. We are merging this through the Android repository. This repository will be updated soon.

**Comment by ZRabat** [comment]
I downloaded the BluetoothChat and had the same problem. 

sirmordred's fixes in the link below WORK!!! I am surprised the original BluetoothChat did not work, thank you for updating sirmordred.

https://github.com/googlesamples/android-BluetoothChat/pull/9/files#diff-802d090bc1a18dfd2af65690f869e5dfR252

**Pull request closed without merging**
